apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  selector:
    app: react
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 32000
      protocol: TCP
      name: http