apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: frontend-air-viewer
  namespace: air-viewer
spec:
  # change this to your DNS
  host: framgia2c.mylabserver.com
  upstreams:
    - name: frontend-air-viewer
      service: hello
      port: 8082
  subroutes:
    - path: /
      action:
        pass: frontend-air-viewer